name: Publish erdjs (alpha / beta)

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: NPM channel
        options: 
        - alpha
        - beta

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      
      - run: npm ci
      - run: npm test
      
      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --access=public --tag=${{ github.event.inputs.channel }}
